language: node_js
node_js:
- lts/*
script: echo "npm test temporarily disabled"
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: jRTTIOisDoHGwnA2E2hkSsj6aMP0So4gdHy6xfVQBHItqH6VDBYJ+qYRTHD86L63jZB3Mr9oYaglp5Dy+m87FRMmgANqEkjBI+epgItXdVjVrpnkMvwmaWrsXVhncLCOEzV+/PVLcjHYjMmudlWYHCpeCr6p7Y6U1mSIrX7BSZf8yFBGG//vZLGCfYRIrt4Ir538hgV3Nzo3HLo76mn8OzGPjEO4JylQ/dmobhE5LrOVxMYBg8aLXXI31OGgqEWweH9+cEBvElMQfw7LBlRw9eSNPeo83pDmVlDPgGFz9XoXTpbleEX6YnkmgNxNk/gsXKRstvBNccMRfrcbi2LTIvD9YDvSA/E03Og/IRwjns673gHn7WEtZvkRkVCwrUj5/ZefF/U1JY9d3LHHimLNTq+THGgvbR4HfsP+zCuNScTR9/yV5rslHAWR05qFrQpDv5TQewa2cvEo7h9/fGhj1xGCIqgtyO5cwynDrYowh5jlDHgF4bY8vDR1lDaH6OmdMIXOX/22iEv/SXYAC+GRUjMLlnehtIg0MAj4BPJzp0Yx1DQZQcBqNjXOkSiu4RmKEyzeN6Kg3u+tDDPOo97cRAtj0gDqEjnbrx8EMCWFx+unC27SU01+tB8dk4tb+d6G6dCu2plrmPwcZOflWx4wuNudIzeubOPIxSieByqreDc=
