language: node_js
node_js:
- lts/*
script: echo "npm test temporarily disabled"
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: hkCxgDws+IJCVG1tM1we0c7xUUXfpL6hSZjh9bDflgR2ua3vSVeUpRNBSN91DoFnKesaxuT++D7V4yu/tkPK0pwUdp3lNvr07A8V+AMlADsvPMshU/EZXd/mlRot/K7T5eAb6H8JSUqhkAxm8JwES3Xb3HNcnc52wrYjMvFFxUh/e4sS4hI/X30UONzJOq2XcYGlKkrCwUcgNIMUidVp4P+8qL19Fz9ueqgjf8ncCwjiSFDvk0GsAWRtbp/dOmfl+YpNYsLSY31zogRnGiyw9+erAWJ3tkwhu+d6IA9ID7cJBuozCM4JsLjfGOfLhWM6iiirw32Bcr4oCFP7MspYsVFo5h17FMmWbhxhvXJvWICfJuVYj+gN+SKTQk0qxHo5CE9xWvVykB+EY4FznpScBLu5wyhRImY6ecg46q+ytnpdqJycbTeijWMw+p9IrPv8vccNnEqifqe+96E7WUmaNJ+fKWUo6mGtGeV1lp3szMgSFlfqkp5U4cyZsrl/8A645vvIwNJEegMlJ5PIBfFR7zageatRE0DK19+iafsPxSxbWmNCxtsUPhPSJCesYDYtokzRPybZhb8Kxl0EeGh2Trt/kzUVP3wtxO5plOECNzG2rXOJZe/dmfYPeG8OlYZP8Icp1fC5YN0eC5Xs50SCMTYZAvd06uo00o1lt8lho7U=
