language: node_js
node_js:
- lts/*
script: echo "npm test temporarily disabled"
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: L+yBj1EfZxw4fNZLa3m7BGUacHCYTcWBV/pdOd/LAmKxSNpPuocDvxNapnqxPlr2KkjfPcMJ8jH3qo1OjsJspQwAtzZSfubvRa1XXadssUlXTMaoccFLIrMxCEzcBCZae0wIt78IubWsQ7ZHrukgdzZbdJzPFmzvflVIJJMXbG58n6XrZqlkWZZbx0/o8oixnrkQ+dWyvu9/H2stvNxR2wqTADmq3S1SKgejkA6QwnF+qc6qdkGhdYOO1En9XxRLdaQr1h1SLl85vpN0pqSUv/pk0e+6MN7ccS0Jn4kUo9OKrYrCeJkau5+Xfc0liM3H7KHA6uqmR3iysY1nL9oskhXH+oLKI0rFUNhIuOu8GIGM6FcB7ozralZP4cOnOXb/uvXVEEvRb9AmYI+oynDj42HJqFBK3Prz7b9k+DGDRz1ZFxVkRHxUo+HykoXhi50f+zxZK9zj3dI4yD4FR0XatN1EpsXZTskYX7onNDwlEaOmGWyc356Vc8qH9TxddcMb8upG1zeR5pfpl4trXXA7jHkpNRVRWPoReGM1sd37Nl72znmV6D2pY5XTCb6FAfvg432YCu4tM8z01YrMsdIh7ftELBXxH2KeoUqE2GCU19gkitmhxcij/wY7Qt3QXN81hLbchi+DxLPzxSL6Ispk4/mvoAVOVu6fqaaaXGC8zyQ=
