language: node_js
node_js:
- lts/*
script: echo "npm test temporarily disabled"
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: KcPEN1cnezCc9PRnZ4NTGBXy6z0p0IbufdidXHTamegDArzebwrQYJTZTQ9+9eLvlRCF3FofHUOGVN1AK/VeZXA/ES7StyIj1w/+VhAwt6AsbUUWYXPY4ZEjO4wtNEnLmUc37A5Bg2HEWJPAgoY+/FTtDuy8TxGI+4MZN3masQaPP2H/lzdJ9X1zC/ekICVEERpTa4L8zP6Rl3g9KANtohFuPn+pV/apwc9ccG2KPaFIoljm3i/lPbnLNp45bjSERin6U7hmc8p5S6qcQcRBEj4tE9JqAPpCmz342NCJFDN9KRaWS85Arj5ILdkp/2UsNefIZYIR3iOlyRiieCemAtKito+/eb/GyzksXDnWu3bqKeZIfOW97WNs0sOC8ojKxzaNnZWlE5D1p6XyxUiqKdCOoLmV0p0cYGtZiTEra/jXZECAW0DHbT+w4o02hzFDxb1Lp/ARlWPBONVcG0QAQNKhuCPPX6LMNvPHtN2dDm7mtFFTpfSNHGcJOQs9+5BoAOrauZ+AW2cIJjJfnK5ba1TqVxJp6DKaLgFpMe8iiUrV8CwtH0N3O+PZs3kbG3qNd6Zb0wU/8gFbo4qpz+i6UDWwyTHx69kzHaBR/GHFmm7vody10desApkIDycs9p8GgxMY/qPXZW4/QBTbvnfDcmE7Pgu1zF7dy6Ppo59CNXA=
