language: node_js
node_js:
- lts/*
script: echo "npm test temporarily disabled"
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: huBHHBmKHkO80mDD6WVoMuOzw8Djd+l9gxIy4rz9jtZSaA4Z1WndzgArOCKE493gucJmFz3Rqsr/oVlwdqLr7J4yzmts3Lc8R1IRz4ehTMz2UYilLdhSrA6iNGG53SoFE0DRgKYNRtcjfyEX3r9z9LX70jUBPa9/YP3n+7eqnKWzwQ4PPo1+8N4XjNa0Jxj7AZJl7gn9Ip8FCZGCv0hMB4knHPk1irySvppjWRrG6EzxjjR/CzCRxiDhZeGPgn7Zy8C+hN6hAfqYfRntI1qh423x6jlG+EVT+LBiUevtLHcf+wdS9PCDajS5hnt9b5+Er+03VuuuEpNlw7tLjXey/TZr3r0FhHRePk/iRd/Mkhv2SRTtbysbIdrdC1oYvYboc/LTdOLMu30Ys7OlhLFVR9C6piB1w6WZGahQ1MxWlJFIWN59yqQEyoQGppP0yudnha9e6qO3dv3blPx/XOmeh2i9r8dO26uScWfL2SI3NLYUcQlA92ReZ/f3dNV2A+CnfWDGH1BRB/iTjtNFJOh5NFmmXnRZZurLjEcH1HgFJWx75sHpsxmZBp3DsX/hooChogpY7so3Gdu9C9v+sDZ67QthNfB25hk9WSgSmMemIbdiD/+ffy5UbeJgPJTiovNdYXAFoTFZTf0FbV95mRVhD+9pY61afQnw8SpenG6At5Q=
